# Generated by Django 5.0.4 on 2024-11-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('number', models.IntegerField()),
                ('collection', models.CharField(max_length=128)),
                ('edition', models.CharField(max_length=128)),
                ('is_backlight', models.BooleanField(default=False)),
            ],
        ),
    ]
